# Server Configuration
server.port=8082

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Management Service URL
management.service.url=http://localhost:8081/api/books